[[constraint]]
  name = "github.com/cjbassi/termui"
  branch = "master"

[[constraint]]
  name = "github.com/docopt/docopt-go"
  branch = "master"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/shirou/gopsutil"
  unused-packages = false
