apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
    - name: grpc
      port: 7900
      targetPort: 7900
    - name: debug
      port: 7901
      targetPort: 7901
  selector:
    app: hello
  type: LoadBalancer
